
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Nestor Marchizone
 */
public class ConversorTemperatura extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConversorTemperatura.class.getName());

    /**
     * Creates new form ConversorTemperatura
     */
    public ConversorTemperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelGeneral = new javax.swing.JPanel();
        jLPedido = new javax.swing.JLabel();
        jTingreso = new javax.swing.JTextField();
        jRtnFahrenheit = new javax.swing.JRadioButton();
        jRtnCelsius = new javax.swing.JRadioButton();
        jRtnKelvin = new javax.swing.JRadioButton();
        jRtnRadianes = new javax.swing.JRadioButton();
        jBConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio 2 de Celcius a Fahrenhei");
        setPreferredSize(new java.awt.Dimension(400, 300));

        jLPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPedido.setText("Ingrese temperatura en grados");
        jLPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTingreso.setPreferredSize(new java.awt.Dimension(20, 30));
        jTingreso.addActionListener(this::jTingresoActionPerformed);

        buttonGroup1.add(jRtnFahrenheit);
        jRtnFahrenheit.setText("Fahrenheit");

        buttonGroup1.add(jRtnCelsius);
        jRtnCelsius.setText("Celsius");

        buttonGroup1.add(jRtnKelvin);
        jRtnKelvin.setText("Kelvin");

        buttonGroup1.add(jRtnRadianes);
        jRtnRadianes.setText("Radianes");

        jBConvertir.setText("Convertir");
        jBConvertir.addActionListener(this::jBConvertirActionPerformed);

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBConvertir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelGeneralLayout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRtnCelsius)
                                .addComponent(jRtnRadianes))))
                    .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRtnFahrenheit)
                        .addComponent(jTingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRtnKelvin)))
                .addGap(100, 100, 100))
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRtnCelsius)
                    .addComponent(jRtnFahrenheit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRtnRadianes)
                    .addComponent(jRtnKelvin))
                .addGap(18, 18, 18)
                .addComponent(jBConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConvertirActionPerformed
        
        try {

            double celsius = Double.parseDouble(jTingreso.getText().trim());

            double resultado;
            String unidad;

            if (jRtnFahrenheit.isSelected()) {

                resultado = celsius * 9.0 / 5.0 + 32;
                unidad = "Fahrenheit";

            } else if (jRtnCelsius.isSelected()) {

                resultado = celsius;
                unidad = "Celsius";

            } else if (jRtnKelvin.isSelected()) {

                resultado = celsius + 273.15;
                unidad = "Kelvin";

            } else if (jRtnRadianes.isSelected()) {

                resultado = celsius * Math.PI / 180;
                unidad = "Radianes";

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Seleccione una unidad de conversión",
                        "Aviso",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
            }

            JOptionPane.showMessageDialog(
                    this,
                    "El resultado es: " + resultado + " " + unidad
            );

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Dato incorrecto. Ingrese un valor numérico válido",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jBConvertirActionPerformed

    private void jTingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTingresoActionPerformed
        jBConvertir.doClick();
    }//GEN-LAST:event_jTingresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConversorTemperatura().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBConvertir;
    private javax.swing.JLabel jLPedido;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JRadioButton jRtnCelsius;
    private javax.swing.JRadioButton jRtnFahrenheit;
    private javax.swing.JRadioButton jRtnKelvin;
    private javax.swing.JRadioButton jRtnRadianes;
    private javax.swing.JTextField jTingreso;
    // End of variables declaration//GEN-END:variables
}
